package frc.robot.configuration;

public enum CANDevice {
	
	SWERVE_FRONT_LEFT_DRIVE_MOTOR_CONTROLLER(1),
	
	SWERVE_FRONT_LEFT_STEER_MOTOR_CONTROLLER(2),
	
	SWERVE_FRONT_RIGHT_DRIVE_MOTOR_CONTROLLER(3),
	
	SWERVE_FRONT_RIGHT_STEER_MOTOR_CONTROLLER(4),
	
	SWERVE_REAR_LEFT_DRIVE_MOTOR_CONTROLLER(5),
	
	SWERVE_REAR_LEFT_STEER_MOTOR_CONTROLLER(6),
	
	SWERVE_REAR_RIGHT_DRIVE_MOTOR_CONTROLLER(7),
	
	SWERVE_REAR_RIGHT_STEER_MOTOR_CONTROLLER(8),
	
	SWERVE_FRONT_LEFT_STEER_ENCODER(9),
	
	SWERVE_FRONT_RIGHT_STEER_ENCODER(10),
	
	SWERVE_REAR_LEFT_STEER_ENCODER(11),
	
	SWERVE_REAR_RIGHT_STEER_ENCODER(12),
	
	TURRET_UPPER_WHEEL_MOTOR_CONTROLLER(13),
	
	TURRET_LOWER_WHEEL_MOTOR_CONTROLLER(14),
	
	PIGEON_IMU(15),
	
	TURRET_HEADING_MOTOR_CONTROLLER(16),
	
	INDEXER_MOTOR_CONTROLLER(17),
	
	CLIMBER_MOTOR_CONTROLLER(18),
	
	INTAKE_LEFT_EXTENSION_MOTOR_CONTROLLER(19),
	
	INTAKE_RIGHT_EXTENSION_MOTOR_CONTROLLER(20),
	
	INTAKE_ROLLER_MOTOR_CONTROLLER(21);
	
	public final int id;
	
	CANDevice(int id) {
		
		this.id = id;
		
	}
	
}
